version: "3.9"
services:
  mc:
    build: .
    restart: unless-stopped
    volumes:
      - ./data/world:/root/world
      - ./data/ops.json:/root/ops.json
      - ./data/backups:/root/backups

      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
    - "25565:25565"
    stdin_open: true
    tty: true